version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt/live/niutechnology.com.br/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/niutechnology.com.br/privkey.pem:/etc/ssl/private/privkey.pem:ro
    depends_on:
      - dotnet
    networks:
      - my-niutecklandpage

  dotnet:
    container_name: dotnet
    build:
      context: ./.niutech  # Caminho para o diretório que contém o Dockerfile1
      dockerfile: dockerfile-build  # Nome do Dockerfile, assumindo que está na pasta niutech
    volumes:
      - /var/lib/docker/volumes/niutecklandpage_prd_app/_data:/app
    ports:
      - "5001:8080"
    networks:
      - my-niutecklandpage

networks:
  my-niutecklandpage:
